services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - mon_reseau
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: mon-serveur-web
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "8080:80"
    networks:
      - mon_reseau
    depends_on:
      - db

networks:
  mon_reseau:
    driver: bridge

volumes:
  db_data:
    external: false